# WARNING - Generated by {fusen} from dev/flat_package.Rmd: do not edit by hand

test_that("permut_pval", {
    MatX <- matrix(rnorm(100), nrow = 25, ncol = 4)
    MatY <- matrix(rnorm(125), nrow = 25, ncol = 5) + 10
    
    n_perm <- 1000
    stat <- "mo"
    res <- permut_pval(MatX, MatY, n_perm, stat)
    checkmate::expect_list(res, len = 1)
    checkmate::qassert(res[[1]], "N1[0,1]")
    
    n_perm <- 1000
    stat <- "hkr"
    res <- permut_pval(MatX, MatY, n_perm, stat)
    checkmate::expect_list(res, len = 1)
    checkmate::qassert(res[[1]], "N2[0,1]")
    
    stat <- c("mo", "med", "wmw", "hkr", "cff")
    res <- permut_pval(MatX, MatY, n_perm, stat)
    checkmate::expect_list(res, len = length(stat))
    checkmate::qassert(res[[1]], "N1[0,1]")
    checkmate::qassert(res[[2]], "N1[0,1]")
    checkmate::qassert(res[[3]], "N1[0,1]")
    checkmate::qassert(res[[4]], "N2[0,1]")
    checkmate::qassert(res[[5]], "N1[0,1]")
})
