# WARNING - Generated by {fusen} from /dev/flat_package.Rmd: do not edit by hand

#' List `funStatTest` package contributors
#' 
#' @keywords internal
#'
#' @rdname authorship
#' 
#' @author
#' Zaineb Smida
#' Ghislain DURIF
#' Lionel Cucala
#' @noRd
authorship <- function() {}
