# WARNING - Generated by {fusen} from dev/flat_package.Rmd: do not edit by hand

#' List `funStatTest` package contributors
#' 
#' @keywords internal
#'
#' @rdname funStatTest_authors
#' 
#' @author Zaineb Smida, Ghislain DURIF, Lionel Cucala
#' @importFrom utils citation
#' @export
funStatTest_authors <- function() {citation("funStatTest")}
